config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :facilities do
    collection do
      post:confirm
      get:search
    end
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy,:index]
  get 'top/index'
  root 'top#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_scope :user do
    post 'users/admin_guest_sign_in', to: 'users/sessions#adomin_guest_sign_in'
  end

  resources :users, only: [:show] do
   member do
      get :following, :followers
    end
 end
  resources :conversations do
    resources :messages
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :facility
  belongs_to :user
  validates :content, presence: true 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :set_facility, only: [:create, :edit, :update]
 before_action :authenticate_user!

  def create
    @comment = @facility.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js{render :index}
      else
        flash.now[:notice] = 'コメントを入力してください'
        format.js { render :error }
      end
    end
  end
  def edit
   @comment = @facility.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
   @comment = @facility.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        format.js { render :error }
      end
    end
  end
   def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:facility_id, :user_id,:content)
  end
  def set_facility
    @facility = Facility.find(params[:facility_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<p class="notice"><%= notice %></p>
<%= form_with(model: [facility, comment],local: false) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{facility.id}" %>
    <%= form.label :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div id="comments-error">
 <%= render 'comments/error_messages', model: @comment %>
</div>
<%= form_with(model: [facility, comment]) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content,class: 'form-control'   %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul >
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <div class="comment-content" id ="this_comment_<%= comment.id  %>"></div>
          <span class="comment_content"><%= comment.content  %></span>
          <% if comment.user.image? %>
            <span><%= image_tag(comment.user.image_url,class:'comment-image')%></span>
          <% else %>
            <span><%= image_tag "noimagehito.png", class:"comment-image" %></span>
          <% end %>
          <span><%= comment.user.name %></span>
        <% if current_user == comment.user %>
         <span><%= link_to "編集", edit_facility_comment_path(facility, comment), remote: true %></span>
         <span><%= link_to "削除", facility_comment_path(comment.facility_id, comment.id), method: :delete, remote: true,
                                       data: { confirm: "本当に削除しますか?"} %></span>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', facility: @facility, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/error.js.erb
$("#comments-error").html("<%= j(render 'comments/error_messages', model: @comment) %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.facility.comments.order(:created_at), facility: @comment.facility }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");