config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :facilities do
    collection do
      post:confirm
      get:search
    end
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy,:index]
  get 'top/index'
  root 'top#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_scope :user do
    post 'users/admin_guest_sign_in', to: 'users/sessions#adomin_guest_sign_in'
  end

  resources :users, only: [:show] do
   member do
      get :following, :followers
    end
 end
  resources :conversations do
    resources :messages
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length:{ maximum: 20 }
  validates :email, presence: true,length:{ maximum: 250 }
  validates :encrypted_password, presence: true,length:{ minimum:6 }
  has_many :facilities,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def follow!(other_user)
   active_relationships.create!(followed_id: other_user.id)
  end
  #フォローしているかどうかを確認する
  def following?(other_user)
   active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      user.admin = false
    end
  end
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "管理者"
      user.admin = true
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
      user = User.guest
      sign_in user
      redirect_to root_path, notice: 'ようこそ、ゲストさん！。'
  end
  def adomin_guest_sign_in
      user = User.admin_guest
       sign_in user
      redirect_to root_path, notice: '管理ユーザーとしてログインしました。'
  end
end
  # GET /resource/sign_in
  # def new
  #   super
  # end
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user,only:[:edit]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @facilities = @user.facilities
  end

  def followers
      @user = User.find(params[:id])
      @users = @user.followers.page(params[:page]).per(5)
      render 'show_follow'
    end

    def following
      @user = User.find(params[:id])
      @users = @user.following.page(params[:page]).per(5)
      render 'show_follower'
    end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを更新しました！"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image,:image_cache, :encrypted_password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    if current_user.id !=  params[:id].to_i
      redirect_to new_user_session_path
    end
  end
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" , class: "btn btn-primary"%>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "フォロー解除" ,class: "btn btn-danger" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user, local:true do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
  
    <%= image_tag @user.image.url ,class: "edit-user" if @user.image && @user.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="name_field">
    <br><%= f.label :name %>
    <br><%= f.text_field :name ,placeholder:"名前を入力" %>
  </div>
  <div class="email_field">
    <br><%= f.label :email %>
    <br><%= f.email_field :email ,placeholder:"snmple@sample.com" %>
  </div>
  <div class="password_field">
    <br><%= f.label :password %>
    <br><%= f.password_field :password ,placeholder:"6字以上で入力してください"  %>
  </div>
  <div class="password_confirmation_field">
    <br><%= f.label :password_confirmation %>
    <br><%= f.password_field :password_confirmation,placeholder:"確認用、もう一度入力してくさい"  %>
  </div>
  <br><%= f.submit "プロフィール編集完了" %>

<%end%>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
<span><%= user.name %></span>
<span><%= render 'follow_form', user: user %></span>
<% end %>

app/views/users/show.html.erb
    <% if @user.id == current_user.id %>
    <h1>プロフィール画面</h1>
    <%else%>
    <h1><%= @user.name %>のページ</h1>
    <% end %>
    <% if @user.image? %>
    <p class="img-circle"><%= image_tag(@user.image.url, class:"user_show_icon") if @user.image && @user.image.url %></p>
    <% else %>
     <%= image_tag "noimagehito.png", class:"user_show_icon"%>
    <% end %>
    <div class="user-nav">
      <% if  current_user.id ==  params[:id].to_i%>
        <p><%= link_to 'プロフィール編集', edit_user_path(@user.id) , class: 'btn btn-primary'%></p>
      <% end %>
      <p><%= link_to 'お気に入り一覧へ',  favorites_path,class:"btn btn-info" %></p>
      <% unless @user == current_user %>
       <p><%= render 'follow_form', user:@user %></p>
        <p><%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post %></p>
        <% end %>
        <p><%= link_to "フォロー:#{@user.following.count}", following_user_path(@user) %></p>
        <p><%= link_to "フォロワー:#{@user.followers.count}", followers_user_path(@user) %></p>
    </div>
<% if @facilities.blank? %>
  <p>↓↓下記に投稿が表示されます↓↓</p>
<% else %>
  <p>↓↓投稿一覧↓↓</p>
  <div class="contents">
    <% @facilities.each do |facility|%>
      <table class="post_facility" style = "width:80%">
        <tr>
          <% if facility.image? %>
            <th rowspan="7"><%= image_tag (facility.image.url(:thumb).to_s)if facility.image && facility.image.url %></th>
          <% else %>
            <th rowspan="7"><%= image_tag "noimagefuukei.png", class:"facility_index_icon" %>
          <% end %>
        </tr>
        <tr>
          <td><strong>投稿者</strong></td>
          <td><%= facility.user.name=%></td>
        </tr>
        <tr>
          <td><strong>施設名</strong></td>
          <td><%= facility.title %></td>
          <td><%= link_to '詳細へ', facility_path(facility.id), class:"btn btn-info btn-sm"%></td>
        </tr>
        <tr>
          <td><strong>タイプ</strong></td>
          <td><%= facility.types %></td>
          <% if facility.user_id == current_user.id %>
          <td><%= link_to '編集へ', edit_facility_path(facility.id),class:"btn btn-success btn-sm"%></td>
          <% end %>
        </tr>
        <tr>
          <td><strong>都道府県</strong></td>
          <td><%= facility.prefecture %></td>
          <% if facility.user_id == current_user.id %>
            <td><%= link_to '削徐', facility_path(facility.id), class:"btn btn-danger btn-sm",method: :delete,data:{ confirm: '本当に削除していいですか？' } %></td>
          <% end %>
        </tr>
        <tr>
          <td><strong>住所</strong></td>
          <td><%= facility.address %></td>
        </tr>
        <tr>
          <td><strong>レビュー</strong></td>
          <td><%= facility.content %></td>
        </tr>
      </table>
    <% end %>
  </div>
<% end %>

app/views/users/show_follow.html.erb
<div class="paginate">
  <strong><%= paginate @users %></strong>
</div>
<div class="follow">
  <div class="follow_container">
 <h3>フォロワー</h3>
    <% @users.each do |follower| %>
      <div class="follow-contents">
        <table class="follow-table">
          <%= link_to user_path(follower) do %>
          <tr>
            <% if follower.image? %>
              <th><%= image_tag follower.image.url, class:'follow-icon' %></th>
            <% else %>
              <th><%= image_tag "noimagehito.png", class:'follow-icon' %></th>
            <% end %>
            <td><%= follower.name %></td>
            <% end %>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="paginate">
  <strong><%= paginate @users %></strong>
</div>
<div class="follow">
  <div class="follower_container">
    <h3>フォロー</h3>
    <% @users.each do |follower| %>
      <div class="follow-contents">
        <table class="follow-table">
          <%= link_to user_path(follower) do %>
          <tr>
            <% if follower.image? %>
              <th><%= image_tag follower.image.url, class:'follow-icon' %></th>
            <% else %>
              <th><%= image_tag "noimagehito.png", class:'follow-icon' %></th>
            <% end %>
            <td><%= follower.name %></td>
            <% end %>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
</div>