config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :facilities do
    collection do
      post:confirm
      get:search
    end
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy,:index]
  get 'top/index'
  root 'top#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_scope :user do
    post 'users/admin_guest_sign_in', to: 'users/sessions#adomin_guest_sign_in'
  end

  resources :users, only: [:show] do
   member do
      get :following, :followers
    end
 end
  resources :conversations do
    resources :messages
  end
end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length:{ maximum: 20 }
  validates :content, presence: true,length:{ maximum: 300 }
  validates :prefecture, presence: true
  presence_values = ['北海道',
                    '青森県','岩手県','宮城県','秋田県','山形県','福島県',
                    '茨城県','栃木県','埼玉県','千葉県','東京都','神奈川県',
                    '新潟県','富山県','石川県','福井県','山梨県','長野県',
                    '岐阜県','静岡県','愛知県','三重県',
                    '滋賀県','京都県','大阪府','兵庫県','奈良県','和歌山県',
                    '鳥取県','島根県','岡山県','広島県','山口県','徳島県','香川県','愛媛県','高知県',
                    '福岡県','佐賀県','長崎県','熊本県','大分県','宮崎県','鹿児島県','沖縄県']
  validates :prefecture, inclusion: { in: presence_values, message: "%{value}欄にない値、空欄は無効です" }
  geocoded_by :address
  geocoded_by :title
  after_validation :geocode, if: :address_changed?,if: :title_changed?
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only:[ :show,:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index,:new, :edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]
  before_action :login_check, only:[:edit,:destroy]
  def index
    @facilities = Facility.all.order(created_at: :desc).page(params[:page]).per(10)
    @q = Facility.ransack(params[:q])
    @faciliti = @q.result(distinct: true)
  end

  def new
    @facility = Facility.new
  end

  def create
    @facility = current_user.facilities.build(facility_params)

    if params[:back]
      render :new
    else
      if @facility.save
        redirect_to facilities_path,notice:"投稿しました"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(facility_id: @facility.id)
    @comments = @facility.comments.order(created_at: :desc)
    @comment = @facility.comments.build
  end


  def edit
  end

  def update
      if @facility.update(facility_params)
        redirect_to facilities_path,notice:"更新しました"
      else
        render :edit
    end
  end

  def destroy
    @facility.destroy
    redirect_to facilities_path,notice:"投稿を削除しました。"
  end
  def confirm
        @facility = current_user.facilities.build(facility_params)
      render :new if @facility.invalid?
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Facility.ransack(params[:q])
  end

  def facility_params
    params.require(:facility).permit(:title,:content,:types,:prefecture,:address,:types, :image,:image_cache,:use_id)
  end

  def set_facility
    @facility  = Facility.find(params[:id])
  end

  def login_check
    unless Facility.find(params[:id]).user_id == current_user.id
      flash[:alert]="不正な操作です"
      redirect_to facilities_path
    end
  end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' 
      confirm_facilities_path
    elsif action_name == 'edit'
      facility_path
    end
  end
end

app/views/facilities/_form.html.erb
<% if @facility.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= @facility.errors.count %>件のエラーがあります。</h2>
    <ul style="list-style:none">
    <% @facility.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @facility, local: true, url: choose_new_or_edit  ) do |form| %>
  <div class="title">
    <br><%= form.label :施設名 %>
    <br><%= form.text_field :title,placeholder:"施設名を入力" %>
  </div>
  <div class="types">
    <br><%= form.label :施設タイプ%>
    <br><%= form.text_field :types,placeholder:"例：屋外・屋内・病院…" %>
  </div>
  <div class="prefecture">
    <br><%= form.label :prefecture%>
    <br> <%= form.select :prefecture,['北海道',
    '青森県','岩手県','宮城県','秋田県','山形県','福島県',
    '茨城県','栃木県','埼玉県','千葉県','東京都','神奈川県',
    '新潟県','富山県','石川県','福井県','山梨県','長野県',
    '岐阜県','静岡県','愛知県','三重県',
    '滋賀県','京都県','大阪府','兵庫県','奈良県','和歌山県',
    '鳥取県','島根県','岡山県','広島県','山口県','徳島県','香川県','愛媛県','高知県',
    '福岡県','佐賀県','長崎県','熊本県','大分県','宮崎県','鹿児島県','沖縄県'], { include_blank: '選択してください' },
    class:"form-select" %>
  </div>
  <div class="address">
    <br><%= form.label :address%>
    <br><%= form.text_field :address,placeholder:"市町村以下住所を入力" %>
  </div>
  <div class="content">
    <br><%= form.label :レビュー %>
    <br><%= form.text_field :content,placeholder:"レビューを入力" %>
  </div>
  <div class="image">
    <br><%= form.label :image %>
    <br><%= form.file_field :image %>
    <br><%= form.hidden_field :image_cache %>
</div>
  <%= form.submit(class:"post_subumit") %>
<% end %>

app/views/facilities/_index.html.erb
<% @facilities.each do |facility|%>
  <table class="post_facility" >
      <tr>
          <% if facility.image? %>
            <%=  link_to facility.image.url, 'data-lightbox': @facility.image do %>
              <th rowspan="7"><%= image_tag (facility.image.url),class:'index_img' if facility.image && facility.image.url %></th>
            <% end %>
          <% else %>
            <th rowspan="7"><%= image_tag "noimagefuukei.png", class:"facility_index_icon" %>
          <% end %>
      </tr>
      <tr>
        <td><strong>投稿者</strong></td>
        <td><%=link_to "#{facility.user.name}", user_path(facility.user.id), class:"btn btn-light" %></td>
      <tr>
        <td><strong>施設名</strong></td>
        <td class="facility_low"><%= facility.title %></td>
        <td><%= link_to '詳細へ', facility_path(facility.id), class:"btn btn-info btn-sm"%></td>
      </tr>
      <tr>
        <td><strong>タイプ</strong></td>
        <td><%= facility.types %></td>
          <% if facility.user_id == current_user.id %>
            <td><%= link_to '編集へ', edit_facility_path(facility.id),class:"btn btn-success btn-sm"%></td>
          <% end %>
      </tr>
      <tr>
        <td><strong>都道府県</strong></td>
        <td><%= facility.prefecture %></td>
          <% if facility.user_id == current_user.id %>
            <td><%= link_to '削徐', facility_path(facility.id), class:"btn btn-danger btn-sm",method: :delete,data:{ confirm: '本当に削除していいですか？' } %></td>
          <% end %>
      </tr>
      <tr>
        <td><strong>住所</strong></td>
        <td><%= facility.address %></td>
      </tr>
      <tr>
        <td><strong>レビュー</strong></td>
        <td class="contents"><%= facility.content %></td>
      </tr>
    </table>
<% end %>

app/views/facilities/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @facility, local: true ) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :types %>
  <%= form.hidden_field :prefecture %>
  <%= form.hidden_field :address %>
  <%= image_tag (@facility.image.url)if @facility.image && @facility.image.url %>
  <%= form.hidden_field :image_cache %>
  <p>タイトル:<%= @facility.title %></p>
  <p>施設タイプ<%= @facility.types %></p>
  <p>都道府県<%= @facility.prefecture %></p>
  <p>住所<%= @facility.address %></p>
  <p>レビュー:<%= @facility.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る" ,name:'back' %>
<% end %>

app/views/facilities/edit.html.erb
<h2>施設情報を編集画面です</h2>
 <%= render 'form' %>

app/views/facilities/index.html.erb
<h2 class="text-center">施設投稿一覧</h2>
<div class="search_field">
  <%= search_form_for @q, url: search_facilities_path do |f| %>
    <strong><%= f.label :title_cont, '施設名・住所' %></strong>
    <strong><%= f.search_field :title_cont,placeholder:"施設名を入力" %></strong>
    <strong><%= f.search_field :prefecture_cont,placeholder:"都道府県を入力" %></strong>
    <strong><%= f.search_field :address_cont,placeholder:"住所を入力" %></strong>
    <strong><%= f.submit '検索' , class:"serch_input" %></strong>
  <% end %>
</div>
<div class="paginate">
  <strong><%= paginate @facilities %></strong>
</div>
<div class="contents">
  <% @facilities.each do |facility|%>
    <table class="post_facility" >
        <tr>
          <% if facility.image? %>
            <th rowspan="7">
              <%=  link_to facility.image.url, 'data-lightbox': facility.image do %>
                <%= image_tag (facility.image.url),class:'index_img' if facility.image && facility.image.url %>
              <% end %>
            </th>
          <% else %>
            <th rowspan="7"><%= image_tag "noimagefuukei.png", class:"facility_index_icon" %>
          <% end %>
      </tr>
      <tr>
        <td><strong>投稿者</strong></td>
        <td><%=link_to "#{facility.user.name}", user_path(facility.user.id), class:"btn btn-light" %></td>
      <tr>
        <td><strong>施設名</strong></td>
        <td class="facility_low"><%= facility.title %></td>
        <td><%= link_to '詳細へ', facility_path(facility.id), class:"btn btn-info btn-sm"%></td>
      </tr>
      <tr>
        <td><strong>タイプ</strong></td>
        <td><%= facility.types %></td>
          <% if facility.user_id == current_user.id %>
            <td><%= link_to '編集へ', edit_facility_path(facility.id),class:"btn btn-success btn-sm"%></td>
          <% end %>
      </tr>
      <tr>
        <td><strong>都道府県</strong></td>
        <td><%= facility.prefecture %></td>
          <% if facility.user_id == current_user.id %>
            <td><%= link_to '削徐', facility_path(facility.id), class:"btn btn-danger btn-sm",method: :delete,data:{ confirm: '本当に削除していいですか？' } %></td>
          <% end %>
      </tr>
      <tr>
        <td><strong>住所</strong></td>
        <td><%= facility.address %></td>
      </tr>
      <tr>
        <td><strong>レビュー</strong></td>
        <td class="contents"><%= facility.content %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/facilities/new.html.erb
<h2>施設を投稿しよう！</h2>
<%= render 'form' %>

app/views/facilities/search.html.erb
<h1>検索結果</h1>
<% if @results.present? %>
  <div class="contents">
    <% @results.each do |facility|%>
      <table class="post_facility" >
        <tr>
          <% if facility.image? %>
            <th rowspan="7"><%= image_tag (facility.image.url),class:'index_img' if facility.image && facility.image.url %></th>
          <% else %>
            <th rowspan="7"><%= image_tag "noimagefuukei.png", class:"facility_index_icon" %>
          <% end %>
        </tr>
        <tr>
          <td><strong>投稿者</strong></td>
          <td><%=link_to "#{facility.user.name}", user_path(facility.user.id), class:"btn btn-light" %></td>
        <tr>
          <td><strong>施設名</strong></td>
          <td class="facility_low"><%= facility.title %></td>
          <td><%= link_to '詳細へ', facility_path(facility.id), class:"btn btn-info btn-sm"%></td>
        </tr>
        <tr>
          <td><strong>タイプ</strong></td>
          <td><%= facility.types %></td>
          <% if facility.user_id == current_user.id %>
            <td><%= link_to '編集へ', edit_facility_path(facility.id),class:"btn btn-success btn-sm"%></td>
          <% end %>
        </tr>
        <tr>
          <td><strong>都道府県</strong></td>
          <td><%= facility.prefecture %></td>
          <% if facility.user_id == current_user.id %>
            <td><%= link_to '削徐', facility_path(facility.id), class:"btn btn-danger btn-sm",method: :delete,data:{ confirm: '本当に削除していいですか？' } %></td>
          <% end %>
        </tr>
        <tr>
          <td><strong>住所</strong></td>
          <td><%= facility.address %></td>
        </tr>
        <tr>
          <td><strong>レビュー</strong></td>
          <td class="contents"><%= facility.content %></td>
        </tr>
      </table>
    <% end %>
  </div>
<% else %>
    <p>該当する投稿は見つかりませんでした🙇。</p>
    <p><%= link_to "一覧へ戻る", facilities_path, class:'btn btn-info'%></p>
<% end %>

app/views/facilities/show.html.erb
<h1>施設詳細</h1>
  <div class="show_contets">
    <p>
      <%= image_tag (@facility.image.url), class:"facility-show-img"if @facility.image && @facility.image.url %>
    </p>
    <p>
      <strong>投稿者</strong>
      <%=link_to "#{@facility.user.name}", user_path(@facility.user.id) %>
    </p>
    <p>
      <strong>施設名</strong>
      <%= @facility.title %>
    </p>
    <p>
      <strong> タイプ</strong>
      <%= @facility.types %>
    </p>
    <p>
      <strong>都道府県</strong>
      <%= @facility.prefecture  %>
    </p>
    <p>
      <strong>住所</strong>
      <%= @facility.address  %>
    </p>
    <p>
      <strong> レビュー</strong>
      <%= @facility.content %>
    </p>
    <strong>地図</strong>
    <% if @facility.latitude.present? %>
      <p id="map"><strong></strong></p>
    <% else %>
      <p>地図を表示できません。詳細な住所を入れてください</p>
    <% end %>
      <script type="text/javascript">
        function initMap() {

          var test ={lat: <%= @facility.latitude %>, lng: <%= @facility.longitude %>};
          var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
            });
          var transitLayer = new google.maps.TransitLayer();
              transitLayer.setMap(map);

          var contentString = '住所：<%= @facility.address %>';
          var contentString = '施設名：<%= @facility.title %>';
          var infowindow = new google.maps.InfoWindow({
              content: contentString
              });

          var marker = new google.maps.Marker({
              position:test,
              map: map,
              title: contentString
              });

          marker.addListener('click', function() {
            infowindow.open(map, marker);
            });
          }
      </script>
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
      </script>
      <strong>コメント欄</strong>
      <div id="comments_area">
        <%= render partial: 'comments/index', locals: { comments: @comments, facility: @facility } %>
      </div>
      <%= render partial: 'comments/form', locals: { comment: @comment, facility: @facility } %>
      <% unless @facility.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'お気に入りする', favorites_path(facility_id: @facility.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
      <%= link_to '戻る', facilities_path,class: 'btn btn-danger'%>
  </div>