config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :facilities do
    collection do
      post:confirm
      get:search
    end
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy,:index]
  get 'top/index'
  root 'top#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_scope :user do
    post 'users/admin_guest_sign_in', to: 'users/sessions#adomin_guest_sign_in'
  end

  resources :users, only: [:show] do
   member do
      get :following, :followers
    end
 end
  resources :conversations do
    resources :messages
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang ="ja">
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <title>MamaPapa</title>
  <meta name="viewport" content="width=devise-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/css?family=Homemade+Apple rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <header>
      <%= link_to root_path, class:"link" do %>
        <h1 class="text-center" calss="title" style= "font-family:Homemade Apple,cursive;">
          <span>M</span>
          <span>a</span>
          <span>m</span>
          <span>a</span>
          <span>P</span>
          <span>a</span>
          <span>p</span>
          <span>a</span>
        </h1>
      <% end%>
      <% if user_signed_in? %>
        <%= link_to "HOME", facilities_path,class: "link" %>
        <%= link_to '新規投稿', new_facility_path, class: "link" %>
        <%= link_to 'プロフィール', user_path(current_user.id), class:"link"%>
        <%= link_to 'お気に入りにした投稿', favorites_path, class:"link" %>
        <%= link_to 'メッセージ一覧', conversations_path, class:"link" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"link" %>
        <%if current_user.try(:admin?)%>
          <span class="adomin_root"><%= link_to '管理画面へ', rails_admin_path,class:"link"%></span>
        <%end%>
        <% else %>
        <%= link_to "新規登録", new_user_registration_path, class: "link" %>
        <%= link_to "ログイン", new_user_session_path,class:"link" %>
        <span class= "guest"><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:"link" %>  </span>

        <span class="admin"><%= link_to '管理ユーザーログイン', users_admin_guest_sign_in_path, method: :post, class:"link"%></span>
      <% end %>
    </header>
    <% if notice %>
     <p class="alert alert-notice"><%= notice %></p>
    <% end %>
      <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
    <% end %>
      <%= yield %>
    <footer>
      <h4 class="text-center">(c)MamaPapa</h4>
    </footer>
  </div>
</body>
</html>